### ISSUE TITLE
Problem in tmoutproc.geometry_utils.align_molecule

### ISSUE THREAD

**Issue by blaschma** [blaschma/tmoutproc#3]
angle = np.arccos(molecule_axis[0] / np.linalg.norm(molecule_axis))
Check if this is wrong and just restricted to a special axis

**Comment by leomart27** [comment]
angle = np.arccos(molecule_axis[0] / np.linalg.norm(molecule_axis)) 
is the angle between your molecule axis and the x-axis. Reminder cos(theta) = <v1,v2>/(|v1|*|v2|). For y-axis you need molecule_axis[1] and for z-axis molecule_axis[2]. For a a general axis, you need a scalar product.

However, I am not sure this is all, that would need to be fixed. The rotation might need some correction as well to generalize for an axis different from x-axis.
